site_name: Unofficial Last.fm API docs
site_description: Unofficial documentation for the Last.fm API

repo_url: https://github.com/lastfm-docs/api-docs
repo_name: lastfm-docs/api-docs

edit_uri: edit/master/docs

theme:
  name: 'material'
  features:
    - content.action.edit
  icon:
    edit: material/pencil
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - toc:
      permalink: true
